<?xml version='1.0' encoding="utf-8" ?>

<!DOCTYPE AED [

<!--
	Application Error Definition DTD.
	For Loadrunner 7.5 and up.
	Mercury Interactive Inc., 2001
-->

<!--
	'Text' element definition
	Contains only parsed character data with no attributes
-->
<!ELEMENT Text (#PCDATA)>

<!--
	'Prefix' element definition
	Contains only parsed character data with no attributes
-->
<!ELEMENT Prefix (#PCDATA)>

<!--
	'Suffix' element definition
	Contains only parsed character data with no attributes
-->
<!ELEMENT Suffix (#PCDATA)>

<!--
	'Rule' element definition. Must include:
		one 'Text' element and afterwards an optional 'Prefix' element and then
		an optional 'Suffix' element

		or

		'one 'Prefix' and afterwards one 'Suffix' element.
	Attributes:
		Name			Rule name, required.
		Level			Rule level, as defined in leveltype entity definition.
						Defualts to 'error'.
		FailIfNotFound	Boolean flag, detrmines whether the script should fail
						if rule is not found. Defaults to 'false'.
		MatchCase		Boolean flag indicating whether the comparison should be
						done Case Sensitive or nor , default is true.
		UseText			Boolean flag indicating whether the catch should be
						matched in 'Text', 'Prefix' and 'Suffix'. Defualts to 'true'.
		Type			What is the type of the rule , can be a regular rule that go over data 
						from the net (value = 'std') or an alert rule that go over alerts that are 
						being displayed (value = 'alert'). default is 'std'.
-->
<!ELEMENT Rule ((Text,Prefix?,Suffix?)|(Prefix,Suffix))>
<!ATTLIST Rule
	Name			CDATA				#REQUIRED
	Level			(disabled|error)	'error'
	FailIfNotFound	(true|false)		'false'
	MatchCase		(true|false)		'true'
	UseText			(true|false)		'true'
	Type			(std|alert)			#IMPLIED
	>

<!--
	'Application' element definition. Must include at least one 'Rule' element inside.
	Attributes:
		Name			Application name, required.
		Enabled			Boolean flag indicating whether the application is enabled.
						Defaults to 'true'.
-->
<!ELEMENT Application (Rule*)>
<!ATTLIST Application
	Name		CDATA			#REQUIRED
	Enabled		(true|false)	'true'
	StampTime	CDATA			#REQUIRED
	StampHost	CDATA			#REQUIRED
	>

<!--
	'AED' (root) element definition. Must include at least one 'Application' element inside.
	Attributes:
		LrVersion				Loadrunner version, optional.
		FileVersionInstallation	Corresponding installation file level, optional.
		FileVersionDefaults		OBSOLETE.  Was corresponding defaults file level, optional.
		Saved					The file has been saved, optional.
-->
<!ELEMENT AED (Application*)>
<!ATTLIST AED
	LrVersion				CDATA					#IMPLIED
	FileVersionInstallation	CDATA					#IMPLIED
	Saved					(true|false)			'false'
	>

]>
<AED LrVersion="7.6" FileVersionInstallation="7">
	<Application Name="IIS_ASP" Enabled="false" StampTime="12345" StampHost="miyaumil">
		<Rule Name="VBScript_Runtime" FailIfNotFound="false" MatchCase="false" UseText="true" Level="error">
			<Text>Microsoft VBScript runtime</Text>
		</Rule>
	</Application>
	<Application Name="PeopleSoftCommonErrors" Enabled="false" StampTime="60274" StampHost="miyaumil">
		<Rule Name="AnErrorHasOcurred" FailIfNotFound="false" MatchCase="false" UseText="true" Level="error">
			<Text>&lt;title&gt;An error has occurred.&lt;/title&gt;</Text>
		</Rule>
		<Rule Name="AppServerDown" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>The application server is down at this time</Text>
		</Rule>
		<Rule Name="CouldNotOpenRegistry" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Could not open registry</Text>
		</Rule>
		<Rule Name="ErrorGettingContent" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Error getting content</Text>
		</Rule>
		<Rule Name="NotAuthorizedForPage" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>You are not authorized for this page</Text>
		</Rule>
		<Rule Name="PageExpired" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Page has expired</Text>
		</Rule>
		<Rule Name="UnableToGetDocument" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Unable to get document</Text>
		</Rule>
	</Application>
	<Application Name="PeopleSoftLessCommonErrors" Enabled="false" StampTime="60273" StampHost="suzanil">
		<Rule Name="BadContentType" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Bad content type for pagelet. Pagelet content must be text. Found content type for pagelet:</Text>
		</Rule>
		<Rule Name="ContactSysAdmin" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Please contact your System Administrator</Text>
		</Rule>
		<Rule Name="ContentIDNotFoundInURL" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Invalid URL - no ContentID found in URL</Text>
		</Rule>
		<Rule Name="ContentTypeErrorInURL" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Invalid URL - unknown Content Type or no Content Type found in URL</Text>
		</Rule>
		<Rule Name="CouldNotGetRegistryFromSession" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Could not get registry from session</Text>
		</Rule>
		<Rule Name="DataReceivedCorrupt" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Data received is corrupt</Text>
		</Rule>
		<Rule Name="DefaultPortalUndefined" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Portal database setup is incomplete.  The Default portal is not defined.  Please contact your system administrator</Text>
		</Rule>
		<Rule Name="ErrorReceivingFile" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Error receiving file</Text>
		</Rule>
		<Rule Name="ErrorWhileAccessingTargetPage" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Error occurred while accessing target page:</Text>
		</Rule>
		<Rule Name="ExceptionStackTrace" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Exception stack trace:</Text>
		</Rule>
		<Rule Name="FileAttachmentFailed" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>File attachment failed</Text>
		</Rule>
		<Rule Name="FileNotFound" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>File not found</Text>
		</Rule>
		<Rule Name="FileNotFoundOrEmpty" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>File not found or file received has length zero</Text>
		</Rule>
		<Rule Name="FileTransferFailed" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>File transfer failed</Text>
		</Rule>
		<Rule Name="IdAndPasswordRequired" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>User ID and Password are required</Text>
		</Rule>
		<Rule Name="IdOrPasswordInvalid" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Your User ID and/or Password are invalid</Text>
		</Rule>
		<Rule Name="ImproperlyFormedURL" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Improperly formed URL</Text>
		</Rule>
		<Rule Name="MalformedURL" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Content contains malformed URL</Text>
		</Rule>
		<Rule Name="NoDiskSpaceAppServer" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>No disk space on Application Server</Text>
		</Rule>
		<Rule Name="NodeNotFoundInURL" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Invalid URL - no Node found in URL</Text>
		</Rule>
		<Rule Name="NotSupportedByBrowser" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>not supported by this browser</Text>
		</Rule>
		<Rule Name="NullRequestReceived" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Null request received</Text>
		</Rule>
		<Rule Name="PageReachedInError" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Warning:  This page was reached in error</Text>
		</Rule>
		<Rule Name="ParserFailure" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Parser failure for</Text>
		</Rule>
		<Rule Name="PortalAppServerNotFound" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Could not create session: portalappserver not found in configuration.properties</Text>
		</Rule>
		<Rule Name="PortalDBSetupIncomplete" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Portal database setup is incomplete.  A local node has not been defined.  Please contact your system adminstrator</Text>
		</Rule>
		<Rule Name="PortalNotFoundInURL" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Invalid URL - no Portal found in URL</Text>
		</Rule>
		<Rule Name="ProvidersNotInitialized" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>The Portal Registry Content Providers have not been initialized.  Please contact your System Adminstrator</Text>
		</Rule>
		<Rule Name="ReportRepositoryDisabled" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>The Report Repository has been disabled</Text>
		</Rule>
		<Rule Name="SchemeMismatch" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Scheme mismatch - unable to access content through https when the portal is accessed through http.  Log in to the portal over https to view this content</Text>
		</Rule>
		<Rule Name="ServerError" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>PeopleSoft Server Error</Text>
		</Rule>
		<Rule Name="SessionIsNull" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Session is null</Text>
		</Rule>
		<Rule Name="UnableConnectSession" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Unable to connect session for</Text>
		</Rule>
		<Rule Name="UnableCreateSession" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Unable to create session for</Text>
		</Rule>
		<Rule Name="UnableFindDefaultHomePage" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Unable to find default home page</Text>
		</Rule>
		<Rule Name="UnableProxyContent" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Unable to proxy content for</Text>
		</Rule>
		<Rule Name="UnableSignonToServer" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Unable to signon to server</Text>
		</Rule>
		<Rule Name="UnableToOpenFile" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Unable to open file</Text>
		</Rule>
		<Rule Name="UnableUseDocumentAsPagelet" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Unable to use document as pagelet</Text>
		</Rule>
		<Rule Name="UnauthorizedViewReport" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>You are not authorized to view the report(s)</Text>
		</Rule>
		<Rule Name="UnknownError" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Unknown error occurred.  Unable to get content</Text>
		</Rule>
		<Rule Name="UnknownNodeNameInURL" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Unknown Node name in URL</Text>
		</Rule>
		<Rule Name="UnknownhHost" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Unknown host</Text>
		</Rule>
		<Rule Name="UnrecoverableError" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>The page you were accessing experienced an unrecoverable error.  You may have lost all recent work since your last save.  If your problem persists, please contact the System Administrator.</Text>
		</Rule>
		<Rule Name="psHomeNotFoundInURL" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Invalid URL - no psHome found in URL</Text>
		</Rule>
	</Application>
	<Application Name="Siebel" Enabled="false" StampTime="1080758775" StampHost="nreynold">
		<Rule Name="Bad_Password_1" FailIfNotFound="false" MatchCase="false" UseText="true" Level="error">
			<Text>(SBL-UIF-00272)</Text>
		</Rule>
		<Rule Name="Bad_Password_2" FailIfNotFound="false" MatchCase="false" UseText="true" Level="error">
			<Text>(SBL-UIF-00271)</Text>
		</Rule>
		<Rule Name="Bad_Password_3" FailIfNotFound="false" MatchCase="false" UseText="true" Level="error">
			<Text>(SBL-SFR-00106)</Text>
		</Rule>
		<Rule Name="Detected_Error" FailIfNotFound="false" MatchCase="false" UseText="true" Level="error">
			<Text>We detected an Error</Text>
		</Rule>
		<Rule Name="Page_Not_Displayed" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>The page cannot be displayed</Text>
		</Rule>
		<Rule Name="Server_Busy" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>The server you are accessing is either busy</Text>
		</Rule>
		<Rule Name="Server_Busy_77" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>The server you are trying to access is either busy</Text>
		</Rule>
		<Rule Name="Session_Timeout" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>Your session timed out because you were idle for too long.</Text>
		</Rule>
		<Rule Name="Status_Error1" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>`Status`Error`</Text>
		</Rule>
		<Rule Name="Status_Error2" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>^Status^Error^</Text>
		</Rule>
		<Rule Name="Status_Error3" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>~Status~Error~</Text>
		</Rule>
		<Rule Name="Status_Error4" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>[Status[Error[</Text>
		</Rule>
		<Rule Name="Status_Error5" FailIfNotFound="false" MatchCase="true" UseText="true" Level="error">
			<Text>6*Status5*Error</Text>
		</Rule>
	</Application>
</AED>
